package de.uni.bamberg.wiai.minf.forflow.datagenerator.view.dialog;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Iterator;

import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.AbstractTableModel;

import org.jdesktop.application.Action;

/**
 * <b>About</b> class represents the usual <i>about</i> dialog in programs.
 * It informs the eager user about the usual stuff.
 * 
 * @author Michael Munz
 * @version 0.1
 * @since Apr/05/09
 */
public class About extends JDialog
{
	/**
	 * ID generated by Eclipse
	 */
	private static final long serialVersionUID = 5457591916050491040L;

	/**
	 * constructor passes the main frame to its superclass.
	 * 
	 * @param parent
	 */
	public About(Frame parent)
	{
		super(parent);
		
		this.initComponents();
		
		this.initTable();
		this.keyBinding();
	}
	
	/**
	 * initializes the table model.
	 */
	private void initTable()
	{
		this.table_properties.setModel(new TableModelProperties());
		this.table_properties.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		this.table_properties.setColumnSelectionAllowed(false);
		this.table_properties.setRowSelectionAllowed(false);
	}
	
	/**
	 * initializes the key binding on the focused window.
	 * When the <i>ESC</i> button has been pressed, the dialog
	 * is gonna be closed or disposed respectively.
	 */
	private void keyBinding()
	{
		this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
				KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
				"cancel");
		this.getRootPane().getActionMap().put("cancel", new EscAction());
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel_about = new javax.swing.JTabbedPane();
        panel_about = new javax.swing.JPanel();
        label_headline = new javax.swing.JLabel();
        button_close = new javax.swing.JButton();
        label_aboutIcon = new javax.swing.JLabel();
        label_text = new javax.swing.JLabel();
        label_version = new javax.swing.JLabel();
        label_coypright = new javax.swing.JLabel();
        label_basedOn = new javax.swing.JLabel();
        label_developer = new javax.swing.JLabel();
        label_versionNo = new javax.swing.JLabel();
        label_year = new javax.swing.JLabel();
        label_javaVersionNo = new javax.swing.JLabel();
        label_developerName = new javax.swing.JLabel();
        panel_properties = new javax.swing.JPanel();
        scrollPane_table = new javax.swing.JScrollPane();
        table_properties = new javax.swing.JTable();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.uni.bamberg.wiai.minf.forflow.datagenerator.DataGenerator.class).getContext().getResourceMap(About.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(470, 312));
        setResizable(false);

        tabbedPanel_about.setName("tabbedPanel_about"); // NOI18N

        panel_about.setName("panel_about"); // NOI18N

        label_headline.setFont(resourceMap.getFont("label_headline.font")); // NOI18N
        label_headline.setText(resourceMap.getString("label_headline.text")); // NOI18N
        label_headline.setName("label_headline"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(de.uni.bamberg.wiai.minf.forflow.datagenerator.DataGenerator.class).getContext().getActionMap(About.class, this);
        button_close.setAction(actionMap.get("close")); // NOI18N
        button_close.setText(resourceMap.getString("button_close.text")); // NOI18N
        button_close.setName("button_close"); // NOI18N

        label_aboutIcon.setIcon(resourceMap.getIcon("label_aboutIcon.icon")); // NOI18N
        label_aboutIcon.setText(resourceMap.getString("label_aboutIcon.text")); // NOI18N
        label_aboutIcon.setName("label_aboutIcon"); // NOI18N

        label_text.setText(resourceMap.getString("label_text.text")); // NOI18N
        label_text.setName("label_text"); // NOI18N

        label_version.setText(resourceMap.getString("label_version.text")); // NOI18N
        label_version.setName("label_version"); // NOI18N

        label_coypright.setText(resourceMap.getString("label_coypright.text")); // NOI18N
        label_coypright.setName("label_coypright"); // NOI18N

        label_basedOn.setText(resourceMap.getString("label_basedOn.text")); // NOI18N
        label_basedOn.setName("label_basedOn"); // NOI18N

        label_developer.setText(resourceMap.getString("label_developer.text")); // NOI18N
        label_developer.setName("label_developer"); // NOI18N

        label_versionNo.setText(resourceMap.getString("label_versionNo.text")); // NOI18N
        label_versionNo.setName("label_versionNo"); // NOI18N

        label_year.setText(resourceMap.getString("label_year.text")); // NOI18N
        label_year.setName("label_year"); // NOI18N

        label_javaVersionNo.setText(resourceMap.getString("label_javaVersionNo.text")); // NOI18N
        label_javaVersionNo.setName("label_javaVersionNo"); // NOI18N

        label_developerName.setText(resourceMap.getString("label_developerName.text")); // NOI18N
        label_developerName.setName("label_developerName"); // NOI18N

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_aboutIcon)
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_headline, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(label_text, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_aboutLayout.createSequentialGroup()
                                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_version)
                                    .addComponent(label_coypright)
                                    .addComponent(label_basedOn)
                                    .addComponent(label_developer))
                                .addGap(25, 25, 25)
                                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_developerName)
                                    .addComponent(label_javaVersionNo)
                                    .addComponent(label_year)
                                    .addComponent(label_versionNo)))
                            .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)))
                .addContainerGap())
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_aboutIcon)
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addComponent(label_headline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_text)
                        .addGap(30, 30, 30)
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_version)
                            .addComponent(label_versionNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_coypright)
                            .addComponent(label_year))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_basedOn)
                            .addComponent(label_javaVersionNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_developer)
                            .addComponent(label_developerName))))
                .addGap(18, 18, 18)
                .addComponent(button_close)
                .addGap(38, 38, 38))
        );

        tabbedPanel_about.addTab(resourceMap.getString("panel_about.TabConstraints.tabTitle"), panel_about); // NOI18N

        panel_properties.setName("panel_properties"); // NOI18N

        scrollPane_table.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane_table.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane_table.setName("scrollPane_table"); // NOI18N

        table_properties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_properties.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_properties.setName("table_properties"); // NOI18N
        table_properties.setPreferredSize(new java.awt.Dimension(430, 300));
        table_properties.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_properties.getTableHeader().setReorderingAllowed(false);
        scrollPane_table.setViewportView(table_properties);

        javax.swing.GroupLayout panel_propertiesLayout = new javax.swing.GroupLayout(panel_properties);
        panel_properties.setLayout(panel_propertiesLayout);
        panel_propertiesLayout.setHorizontalGroup(
            panel_propertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_table, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_propertiesLayout.setVerticalGroup(
            panel_propertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_table, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabbedPanel_about.addTab(resourceMap.getString("panel_properties.TabConstraints.tabTitle"), panel_properties); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel_about, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel_about, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	@Action
	public void close()
	{
		this.dispose();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_close;
    private javax.swing.JLabel label_aboutIcon;
    private javax.swing.JLabel label_basedOn;
    private javax.swing.JLabel label_coypright;
    private javax.swing.JLabel label_developer;
    private javax.swing.JLabel label_developerName;
    private javax.swing.JLabel label_headline;
    private javax.swing.JLabel label_javaVersionNo;
    private javax.swing.JLabel label_text;
    private javax.swing.JLabel label_version;
    private javax.swing.JLabel label_versionNo;
    private javax.swing.JLabel label_year;
    private javax.swing.JPanel panel_about;
    private javax.swing.JPanel panel_properties;
    private javax.swing.JScrollPane scrollPane_table;
    private javax.swing.JTabbedPane tabbedPanel_about;
    private javax.swing.JTable table_properties;
    // End of variables declaration//GEN-END:variables
    
    /**
     * inner class defines the table model of properties for
     * the register pane <i>properties</i>
     */
    private class TableModelProperties extends AbstractTableModel
    {
		/**
		 * ID generated by Eclipse
		 */
		private static final long serialVersionUID = -2268840613344836559L;

		@Override
		public int getColumnCount()
		{
			return 2;
		}

		@Override
		public int getRowCount()
		{
			return System.getProperties().size();
		}
		
		@Override
		public String getColumnName(int column)
		{
			if(column == 0)
			{
				return "Property";
			}
			else
			{
				return "Value";
			}
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex)
		{
			Iterator<Object> iterator = System.getProperties().keySet().iterator();
			
			int i=0;
			
			while(iterator.hasNext())
			{
				Object key = iterator.next();
				
				if(i == rowIndex)
				{
					if(columnIndex == 0)
					{
						return key;
					}
					else
					{
						return System.getProperties().getProperty(key.toString());
					}
				}
				
				i++;
			}
			
			return null;
		}
    }
    
    /**
     * Handles the action event, when button <i>ESC</i> has been pressed.
     * This is done by key binding to respond within the focused window.
     * </p>
     * When <i>ESC</i> is pressed, the dialog is gonna be disposed.
     * 
     * @author Michael Munz
     * @version 0.1
     * @since Apr/09/09
     */
    private class EscAction extends AbstractAction
    {
		/**
		 * ID generated by Eclipse
		 */
		private static final long serialVersionUID = 6939585627658024367L;

		@Override
		public void actionPerformed(ActionEvent arg0)
		{
			dispose();
		}
    }
}