package de.uni.bamberg.wiai.minf.forflow.datagenerator.controller.datageneration.filltype;

/**
 * This is an enumeration of possible levels of details by the generation
 * of dates. Dates have an interval with an lower and an upper bound.
 * But the values in these intervals can be handled in different ways.
 * It is possible to generate dates with only a year, or a year and a month
 * or even a year, a month and a day.
 * </p>
 * <font size=6><b>Level of details</b></font></br>
 * Level of details specifies how the generated dates will look like.
 * There're different levels available:
 * <ul>
 * 		<li><b>year</b></li> has the lowest level of detail.
 * 		Only a year in the interval will be generated.
 * 		<li><b>month</b></li> The level of detail is between
 * 		year and day. The generated date has a year and a month field.
 * 		<li><b>day</b></li> has the highest level of detail.
 * 		When this level has been chosen, all fields are generated.
 * 		That is a year, a month and a day.
 * </ul>
 * </p>
 * <font size=6><b>Example</b></font></br> 
 * Suppose you've got the interval of [2007, 2009].
 * In terms of a date a level of details defines the possible
 * values for this interval.
 * </p>
 * <font size=4><b>Year</b></font></br>
 * If the level of detail is set to <i>year</i> then the
 * values will be only the years in the interval.</br>
 * <font color=red>2007</font></br>
 * <font color=red>2008</font></br>
 * <font color=red>2009</font></br>
 * </p>
 * <font size=4><b>Month</b></font></br>
 * The available values will be greater if the details
 * of <i>month</i> are enabled. Then we've 36 values.
 * </br>
 * <code>3 years * 12 month</code> = 36 month (values).</br>
 * <font color=red>January</font></br>
 * <font color=red>...</font></br>
 * <font color=red>December</font></br>
 * </p>
 * <font size=4><b>Day</b></font></br>
 * The most details dates are generated by the <i>day</i> level.
 * For each year the days are calculated. That makes 1095 days
 * in the example used above. 
 * 
 * @author Michael Munz
 * @version 0.1
 * @since May/12/09
 */
public enum DateInterval
{
	/**
	 * splits the date interval into the number of years
	 * </p>
	 * <font size=6><b>Example</b></font></br>
	 * Suppose you have an interval of [2007, 2009].
	 * If you wanna split the given interval only into
	 * years the available values would be:</br>
	 * <font color=red>2007</font></br>
	 * <font color=red>2008</font></br>
	 * <font color=red>2009</font></br>
	 * </p>
	 * <font size=6><b>When to use?</b></font></br>
	 * Use this option when the dates to generate should only
	 * consist of years.
	 * The generated time stamp for a facet <i>modified</i> looks like this:</br>
	 * <code>date modified:</code> <font color=red>year</font
	 */
	YEAR,
	
	/**
	 * splits the date interval into month.
	 * It is medium detailed.
	 * </p>
	 * <font size=6><b>Example</b></font></br>
	 * Suppose you've got the interval [2007, 2009].
	 * In terms of a date interval with the detail of
	 * month you would get the following values: </br>
	 * <font color=red>January</font></br>
	 * <font color=red>...</font></br>
	 * <font color=red>December</font></br>
	 * The above values depict only the values available once
	 * and not for all years, but for one. Of course, you would
	 * get the month of all years. In the example here there're
	 * three years so <b>3 * 12 = 36</b> month. In other words,
	 * 36 values are available and it's more detailed as years. 
	 * </p>
	 * <font size=6><b>When to use?</b></font></br>
	 * Use this approach when a date should be generated with a year
	 * and a month.
	 * The generated time stamp for a facet <i>modified</i> looks like this:</br>
	 * <code>date modified:</code> <font color=red>month/year</font
	 */
	MONTH,
	
	/**
	 * splits the date interval into days.
	 * This is the most detailed way of possible splitting.
	 * </p>
	 * <font size=6><b>Example</b></font></br>
	 * Imagine you've the following interval [2007, 2009].
	 * In terms of a date interval and with the details of days
	 * you would get for each year in the interval the days.
	 * </p>
	 * <code>3 * 365 = 1095 days</code>
	 * </p>
	 * In the example above are three years multiplied by 365 days
	 * per year makes a total amount of 1095 days as possible values.
	 * </p>
	 * <font size=6><b>When to use?</b></font></br>
	 * Use days when you want dates with a year, a month and a day.
	 * The generated time stamp for a facet <i>modified</i> looks like this:</br>
	 * <code>date modified:</code> <font color=red>month/day/year</font
	 */
	DAY;
}